# Generated by Django 2.1.14 on 2019-12-02 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=22)),
                ('ccredit', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course',
                'ordering': ['cno'],
            },
        ),
        migrations.CreateModel(
            name='SC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_design.Course')),
            ],
            options={
                'db_table': 'sc',
                'ordering': ['sno'],
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=20)),
                ('sgender', models.BooleanField(default=True)),
                ('sbirth', models.DateTimeField()),
                ('sphone', models.CharField(max_length=11)),
                ('sdate', models.DateTimeField()),
                ('saddress', models.CharField(max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['sno'],
            },
        ),
        migrations.AddField(
            model_name='sc',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_design.Students'),
        ),
        migrations.AlterUniqueTogether(
            name='sc',
            unique_together={('sno', 'cno')},
        ),
    ]
