# Generated by Django 2.1.14 on 2019-12-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['username'],
            },
        ),
    ]
